### ISSUE TITLE
Add a setting or view button that hides/shows channels with no unread posts

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#124]
It might be nice when there are a LOT of channels to actually hide all the channels that don’t have any unread posts.

This can be seen in reader apps like fiery feeds and reeder. They do this by having a bottom bar that has “starred, unread and all”. While I don’t think starred is something to do, it might be nice to have some type of “toggle” that switches between showing all channels and just read/unread channels.

Second questions is should this toggle also affect the channels themselves?

**Comment by EdwardHinkle** [comment]
Interesting Reeder chose to have the setting affect both the channel view and the timeline view

But Fiery Feeds actually only has the setting affect the channel view

**Comment by EdwardHinkle** [comment]
Awesome! Great to hear other areas where this has worked well. Do you have any thoughts between it just applying to channels and it applying to the posts? What does your IRC client do?

(Originally published at: https://eddiehinkle.com/2018/02/25/5/reply/)

**Comment by aaronpk** [comment]
I do think it should be a preference, tho maybe hidden by default is okay. The trick is once the channels without new content are hidden, you have to have a way to quickly show them again in case you want to be able to look at old content again.

As for the posts: Slack, IRC clients, as well as Twitter, show all the posts, not just the unread ones. I don't think I personally would use the "show only new posts" feature except in certain cases such as when I suspect there might be some old unread posts that have been buried somehow. I prefer to have some visual indicator about whether a post has been read rather than hiding it completely. In either case, you'd need a quick way to toggle between showing all posts vs showing unread posts.

**Comment by EdwardHinkle** [comment]
Here is an example of Reeder. There is actually a tab bar on the bottom that allows for switch between starred, unread and all. While I don’t know that I want to take up the tab bar space with it, having some simple toggle like this is nice, I think.
I think you’re right though. This toggle should only affect the channels. The posts should be done through an timeline filter (where you can filter more than just the read/unread status)

(Originally published at: https://eddiehinkle.com/2018/02/25/7/reply/)
