### ISSUE TITLE
Just spins when I try to log in

### ISSUE THREAD

**Issue by devilgate** [EdwardHinkle/indigenous-ios#32]
Hi, I’ve got a WordPress site, and after I filled in my URL it just sits with the spinner on the “Authorizing with server” message. I put in my blog URL, http://devilgate.org/blog/ , because that’s where WordPress is hosted.

**Comment by EdwardHinkle** [comment]
Seems like it's an [IndieAuth](https://indieauth.net) set up issue. Have you ever used an IndieAuth login before?

So it looks like the authorization endpoint is set to indieauth.com. IndieAuth.com is an IndieAuth authorization endpoint that uses [RealMeAuth](http://microformats.org/wiki/RelMeAuth).

Option 1: You could either set up RealMeAuth on your site for IndieAuth.com by [adding rel=me to your blog url](https://indieauth.com/setup) http://devilgate.org/blog/

Option 2: You could have your WordPress installation become it's own authorization endpoint for the IndieAuth authentication. 

I'm not as familiar with Option 2, but if that's the way you want to go we can definitely get you set up that way.

**Comment by devilgate** [comment]
Hi Edward,

I haven't really used IndieAuth before -- or maybe I have, since I have 
various `rel=me` references set up on my home page. But it's mentioned 
whenever WordPress prompts me for login, so I figured WP would know 
about it.

However, I tried going to [indieauth.com](https://indieauth.com) and 
logging in using just my domain, http://devilgate.org/, without the 
`blog/` suffix, where WordPress is installed. It found the `rel=me` 
reference for Twitter and logged me in using that.

So I tried the same thing on Indigenous -- using http://devilgate.org/ 
-- and I still get it spinning on "Authorizing with Server".

Any other thoughts?

Cheers,

Martin
-- 
Martin McCallion
http://devilgate.org/blog/
@devilgate

**Comment by EdwardHinkle** [comment]
How do you currently post to your site for micro.blog? Is that through wordpress or the micro.blog app?

**Comment by devilgate** [comment]
Both. Either. It’s a self-hosted WP installation, and posting from Micro.blog and through traditional WP methods both work.  

Cheers,  

Martin  
--  
Martin McCallion  
http://devilgate.org/blog/
@devilgate

**Comment by EdwardHinkle** [comment]
It seems like micro.blog is likely using the wordpress API rather than the micropub endpoint.

I would recommend logging in to https://quill.p3k.io/ it is a micropub client that walks through all the steps to ensure that everything is connected correctly.

I'm thinking the likely scenario is you'll want to copy the following from the <head> of your blog and add it to your devilgate.org site as well:

```
<link rel="micropub" href="http://devilgate.org/blog/?micropub=endpoint">
<link rel="authorization_endpoint" href="https://indieauth.com/auth">
<link rel="token_endpoint" href="https://tokens.indieauth.com/token">
```

The micropub endpoint on wordpress should accept any posts when you login using IndieAuth from your primary domain http://devilgate.org as long as that is the "profile url" of your user within your wordpress.

I haven't used Wordpress with micropub before so I'm not the best at diagnosing Wordpress issues, but I can try my best. I think next steps would be to try posting using Quill as that provides a lot of initial IndieAuth/Micropub set up information. There is also a Wordpress community on the IndieWeb slack that probably knows more than I do about getting micropub working :) https://indieweb.org/discuss
