### ISSUE TITLE
Stuck on "Authorizing with Server"

### ISSUE THREAD

**Issue by barryf** [EdwardHinkle/indigenous-ios#36]
I can enter my site (https://barryfrost.com), authorize with my IndieAuth service (auth.barryfrost.com) and get returned to Indigenous, but from there I just see "Authorizing with Server" and a spinner.

Is there an issue my end that you can see in your logs? Perhaps a return value that I'm missing? Quill, Micropublish, IndieWeb wiki, etc. all log in fine.

**Comment by EdwardHinkle** [comment]
I haven't installed any third party logging software currently so I only get what Apple sends me, which is crash logs. 👎 

Looking at my code, the first two things that come to mind is:
- Are you returning a 200 http status code?
- Are you returning application/x-www-form-urlencode or application/json from your token endpoint? I realized looking through the code for potential issues here that I did not finish the logic for application/json but I'm not presenting a user-facing error for it. So that could be a potential problem

**Comment by EdwardHinkle** [comment]
When I say 200 http status code, I mean in response to a request to your token server

**Comment by barryf** [comment]
Thanks, Eddie. Looking at my logs, yes, there's a 200 from your POST to the token endpoint with the following parameters:
```
access_token: TOKEN,
scope: create,
me: https://barryfrost.com/
```

I use a content-type of `application/x-www-form-urlencoded` unless the Accept header contains `application/json` so that should be OK.

I'll switch to using IndieAuth.com and see if that helps.

**Comment by barryf** [comment]
Logging in completed successfully with IndieAuth.com so it must be something Indigenous doesn't like about my token endpoint! If this is limited to my own server then I'll close this issue.

**Comment by EdwardHinkle** [comment]
It would be good to figure out what Indigenous doesn't like. I'll look into adding some logging in the next build and let you know, that way you can try the next build with your endpoint again and see if the app can tell me what went wrong. I definitely want this to work with more than just IndieAuth.com :) I'll re-open after the next build is pushed so we can revisit

**Comment by barryf** [comment]
Sounds like a good plan, @EdwardHinkle. Thanks. I'll let you get back to issues with the main app.
