### ISSUE TITLE
If in-reply-to is not on a post, but an in-reply-to tag exists in the post, add that to the post’s in-reply-to property 

### ISSUE THREAD

**Issue by EdwardHinkle** [EdwardHinkle/indigenous-ios#91]
Like #89

**Comment by aaronpk** [comment]
Did you find an instance of this? This shouldn't happen by definition, since any in-reply-to Microformats property in the post would cause it to appear in the Microsub post. This is in contrast to photos, where an img tag can exist in the content that does not have u-photo so does not get set as the photo property of the Microsub post

**Comment by EdwardHinkle** [comment]
I have not seen an instance of this. Good to know that this might not be an issue. My main concern was micro.blog posts coming from an RSS feed. I’ll take a closer look to verify everything is as you said and close this if that’s the case.

**Comment by EdwardHinkle** [comment]
Gotcha, this is correct. This is not an issue. Unfortunately, micro.blog posts in the feed don't have any connection to the post that they are a reply to.
